[package]
name = "num-string"
version = "0.1.0"
edition = "2021"

[lib]
name = "num_string"
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.5", default-features = false }